---
- name: Install curl
  apt: name=curl state=present install_recommends=no update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /tmp
    creates: /usr/local/bin/composer
  sudo: no

- name: Move composer
  shell: mv /tmp/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  sudo: yes

# see https://github.com/phpspec/prophecy/issues/153
- name: Update composer (ensure we have the latest version)
  shell: composer self-update
  sudo: yes

- name: Install composer dev dependencies
  shell: composer install
  args:
    chdir: "{{ composer_dir }}"
  when: composer_dir is defined

- name: Make composer installed libraries available on cli
  lineinfile: dest=/home/{{ composer_user }}/.bashrc line="export PATH={{ composer_dir }}/vendor/bin:$PATH" owner={{ composer_user }} group={{ composer_user }}
  when: composer_user is defined
